# CA1 Statistical Techniques for Data Analysis

Dataset: **Data_CA1.csv** - an anonymous survey with 41 responses to 18 questions on the leisure travel habits of people living in Ireland.

The Google form of the survey is: https://docs.google.com/forms/d/e/1FAIpQLSdrzDmbAsnr-aCScCQZNd7D6rMeA9Rdp513igdLuxQqrRo2Ow/viewform?usp=dialog

The data was collected for academic purposes and has been fully anonymised (timestamps were also removed, as they are a potential way to de-anonymise responses).

In [1]:
# Import required libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## 0. Load & clean the data

In [2]:
# Load a dataset
df = pd.read_csv('Data_CA1.csv')

In [3]:
# Having a look at the dataset
df

,Unnamed: 0,Total score,1. What is your gender?,1. What is your gender? [Score],1. What is your gender? [Feedback],2. What is your age?,2. What is your age? [Score],2. What is your age? [Feedback],3. How long have you been living in Ireland?,3. How long have you been living in Ireland? [Score],...,15. What is your preferred way of travelling around Ireland? [Feedback],16. What is the typical length of your leisure trip within Ireland?,16. What is the typical length of your leisure trip within Ireland? [Score],16. What is the typical length of your leisure trip within Ireland? [Feedback],17. Which counties in Ireland have you visited for leisure?,17. Which counties in Ireland have you visited for leisure? [Score],17. Which counties in Ireland have you visited for leisure? [Feedback],"18. Overall, how satisfied are you with the opportunities to explore Ireland?","18. Overall, how satisfied are you with the opportunities to explore Ireland? [Score]","18. Overall, how satisfied are you with the opportunities to explore Ireland? [Feedback]"
0,0,0.00 / 0,Male,-- / 0,NaN,27,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,4 - 7 nights,-- / 0,NaN,Cork;Donegal;Dublin;Galway;Kerry;Kildare;Kilke...,-- / 0,NaN,5,-- / 0,NaN
1,1,0.00 / 0,Male,-- / 0,NaN,28,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Cork;Dublin;Kildare,-- / 0,NaN,5,-- / 0,NaN
2,2,0.00 / 0,Male,-- / 0,NaN,55,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Cork;Donegal;Dublin;Galway;Kerry;Mayo;Sligo;We...,-- / 0,NaN,4,-- / 0,NaN
3,3,0.00 / 0,Female,-- / 0,NaN,29,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,-- / 0,NaN,3,-- / 0,NaN
4,4,0.00 / 0,Female,-- / 0,NaN,29,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,-- / 0,NaN,3,-- / 0,NaN
5,5,0.00 / 0,Male,-- / 0,NaN,28,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Clare;Cork;Dublin;Galway;Kerry;Limerick;Mayo;W...,-- / 0,NaN,4,-- / 0,NaN
6,6,0.00 / 0,Female,-- / 0,NaN,39,-- / 0,NaN,5 - 6 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Kildare;Kilkenny;Waterford;Wexford;Wicklow,-- / 0,NaN,4,-- / 0,NaN
7,7,0.00 / 0,Male,-- / 0,NaN,36,-- / 0,NaN,1 - 2 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Carlow;Cork;Donegal;Dublin;Galway;Limerick;May...,-- / 0,NaN,4,-- / 0,NaN
8,8,0.00 / 0,Male,-- / 0,NaN,29,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Clare;Cork;Dublin;Galway;Wicklow,-- / 0,NaN,3,-- / 0,NaN
9,9,0.00 / 0,Female,-- / 0,NaN,41,-- / 0,NaN,10 + years,-- / 0,...,NaN,1 night,-- / 0,NaN,Clare;Cork;Donegal;Dublin;Galway;Kerry;Kildare...,-- / 0,NaN,5,-- / 0,NaN
10,10,0.00 / 0,Male,-- / 0,NaN,35,-- / 0,NaN,9 - 10 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Cavan;Clare;Cork;Dublin;Galway;Kerry;Kildare;L...,-- / 0,NaN,3,-- / 0,NaN
11,11,0.00 / 0,Female,-- / 0,NaN,36,-- / 0,NaN,7 - 8 years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Donegal;Dublin;Kerry;Kildare;Wicklow,-- / 0,NaN,5,-- / 0,NaN
12,12,0.00 / 0,Female,-- / 0,NaN,26,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,1 night,-- / 0,NaN,Cork;Dublin;Galway;Kildare;Kilkenny;Limerick;M...,-- / 0,NaN,3,-- / 0,NaN
13,13,0.00 / 0,Female,-- / 0,NaN,40,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Dublin;Kildare;Waterford,-- / 0,NaN,3,-- / 0,NaN
14,14,0.00 / 0,Female,-- / 0,NaN,30,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Dublin;Kilkenny;Wicklow,-- / 0,NaN,5,-- / 0,NaN
15,15,0.00 / 0,Male,-- / 0,NaN,33,-- / 0,NaN,9 - 10 years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Cork;Dublin;Galway;Kerry;Kildare;Wexford;Wicklow,-- / 0,NaN,4,-- / 0,NaN
16,16,0.00 / 0,Male,-- / 0,NaN,49,-- / 0,NaN,10 + years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Clare;Cork;Donegal;Kerry;Kilkenny;Limerick;Mea...,-- / 0,NaN,4,-- / 0,NaN
17,17,0.00 / 0,Male,-- / 0,NaN,27,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Cork;Dublin;Galway;Sligo;Waterford;Wexford,-- / 0,NaN,4,-- / 0,NaN
18,18,0.00 / 0,Male,-- / 0,NaN,32,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Cork;Dublin;Galway;Kildare;Kilkenny;Waterford;...,-- / 0,NaN,3,-- / 0,NaN
19,19,0.00 / 0,Female,-- / 0,NaN,33,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Carlow;Dublin;Galway;Kildare;Kilkenny;Limerick...,-- / 0,NaN,5,-- / 0,NaN
20,20,0.00 / 0,Male,-- / 0,NaN,39,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Carlow;Cork;Dublin;Kerry;Kildare;Kilkenny;Lime...,-- / 0,NaN,4,-- / 0,NaN
21,21,0.00 / 0,Female,-- / 0,NaN,42,-- / 0,NaN,10 + years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Clare;Cork;Galway;Kildare;Mayo;Wexford;Wicklow,-- / 0,NaN,5,-- / 0,NaN
22,22,0.00 / 0,Female,-- / 0,NaN,44,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Cork;Kerry;Kildare,-- / 0,NaN,3,-- / 0,NaN
23,23,0.00 / 0,Female,-- / 0,NaN,36,-- / 0,NaN,10 + years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kerry;...,-- / 0,NaN,4,-- / 0,NaN
24,24,0.00 / 0,Male,-- / 0,NaN,32,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,1 night,-- / 0,NaN,Clare;Cork;Donegal;Dublin;Galway;Kerry;Kilkenn...,-- / 0,NaN,5,-- / 0,NaN
25,25,0.00 / 0,Female,-- / 0,NaN,36,-- / 0,NaN,9 - 10 years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Donegal;Kerry;Sligo,-- / 0,NaN,5,-- / 0,NaN
26,26,0.00 / 0,Male,-- / 0,NaN,36,-- / 0,NaN,1 - 2 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Cork;Donegal;Dublin;Galway;Limerick;Mayo;Rosco...,-- / 0,NaN,4,-- / 0,NaN
27,27,0.00 / 0,Male,-- / 0,NaN,40,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Cork;Dublin;Kildare;Waterford,-- / 0,NaN,3,-- / 0,NaN
28,28,0.00 / 0,Non-binary,-- / 0,NaN,48,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Carlow;Cork;Donegal;Dublin;Galway;Kerry;Kildar...,-- / 0,NaN,3,-- / 0,NaN
29,29,0.00 / 0,Female,-- / 0,NaN,26,-- / 0,NaN,5 - 6 years,-- / 0,...,NaN,1 night,-- / 0,NaN,Carlow;Cavan;Cork;Dublin;Galway;Kildare;Limeri...,-- / 0,NaN,4,-- / 0,NaN
30,30,0.00 / 0,Male,-- / 0,NaN,32,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Cork;Dublin;Galway;Kildare;Kilkenny;Limerick;M...,-- / 0,NaN,5,-- / 0,NaN
31,31,0.00 / 0,Male,-- / 0,NaN,33,-- / 0,NaN,9 - 10 years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Dublin;Kerry;Kildare;Wicklow,-- / 0,NaN,3,-- / 0,NaN
32,32,0.00 / 0,Female,-- / 0,NaN,41,-- / 0,NaN,10 + years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Cavan;Clare;Cork;Donegal;Dublin;Galway;Kerry;K...,-- / 0,NaN,5,-- / 0,NaN
33,33,0.00 / 0,Female,-- / 0,NaN,31,-- / 0,NaN,10 + years,-- / 0,...,NaN,1 night,-- / 0,NaN,Cork;Dublin;Galway;Kerry;Kilkenny;Limerick;Sli...,-- / 0,NaN,5,-- / 0,NaN
34,34,0.00 / 0,Male,-- / 0,NaN,27,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Clare;Cork;Donegal;Kerry;Kilkenny;Mayo;Waterfo...,-- / 0,NaN,3,-- / 0,NaN
35,35,0.00 / 0,Female,-- / 0,NaN,29,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kilken...,-- / 0,NaN,3,-- / 0,NaN
36,36,0.00 / 0,Female,-- / 0,NaN,43,-- / 0,NaN,10 + years,-- / 0,...,NaN,1 night,-- / 0,NaN,Clare;Cork;Donegal;Dublin;Galway;Kerry;Kildare...,-- / 0,NaN,5,-- / 0,NaN
37,37,0.00 / 0,Male,-- / 0,NaN,30,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Dublin;Wicklow,-- / 0,NaN,3,-- / 0,NaN
38,38,0.00 / 0,Male,-- / 0,NaN,35,-- / 0,NaN,10 + years,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Dublin;Kerry,-- / 0,NaN,5,-- / 0,NaN
39,39,0.00 / 0,Female,-- / 0,NaN,26,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Clare;Cork;Dublin;Galway;Kerry;Kildare;Leitrim...,-- / 0,NaN,5,-- / 0,NaN
40,40,0.00 / 0,Male,-- / 0,NaN,39,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Carlow;Cork;Dublin;Kerry;Kildare;Kilkenny;Lime...,-- / 0,NaN,4,-- / 0,NaN

In [4]:
df.shape

(41, 56)

In [5]:
df.describe()

,Unnamed: 0,1. What is your gender? [Feedback],2. What is your age?,2. What is your age? [Feedback],3. How long have you been living in Ireland? [Feedback],4. Which county do you currently live in? [Feedback],5. What best describes your current living area? [Feedback],6. What is your household situation? [Feedback],7. Do you have a car in Ireland? [Feedback],8. Would you prefer to spend next holiday in Ireland or abroad? [Feedback],...,11. Who do you usually travel with? [Feedback],12. What is the main purpose of your leisure trips? [Feedback],13. How many leisure trips within Ireland have you taken in the last 12 months?,13. How many leisure trips within Ireland have you taken in the last 12 months? [Feedback],14. What type of Irish destination do you prefer? [Feedback],15. What is your preferred way of travelling around Ireland? [Feedback],16. What is the typical length of your leisure trip within Ireland? [Feedback],17. Which counties in Ireland have you visited for leisure? [Feedback],"18. Overall, how satisfied are you with the opportunities to explore Ireland?","18. Overall, how satisfied are you with the opportunities to explore Ireland? [Feedback]"
count,41.000000,0.0,41.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,41.000000,0.0,0.0,0.0,0.0,0.0,41.000000,0.0
mean,20.000000,NaN,34.804878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.731707,NaN,NaN,NaN,NaN,NaN,4.024390,NaN
std,11.979149,NaN,6.918163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.535706,NaN,NaN,NaN,NaN,NaN,0.851111,NaN
min,0.000000,NaN,26.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,3.000000,NaN
25%,10.000000,NaN,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,3.000000,NaN
50%,20.000000,NaN,33.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,4.000000,NaN
75%,30.000000,NaN,39.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,5.000000,NaN
max,40.000000,NaN,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,NaN,5.000000,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 56 columns):
 #   Column                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                      --------------  -----
 0   Unnamed: 0                                                                                                  41 non-null     int64
 1   Total score                                                                                                 41 non-null     str
 2   1. What is your gender?                                                                                     41 non-null     str
 3   1. What is your gender? [Score]                                                                             41 non-null     str
 4   1. What is your gender? [Feedback]                                                                          0 non-null      float64
 5   2. What is your age?                                                                                        41 non-null     int64
 6   2. What is your age? [Score]                                                                                41 non-null     str
 7   2. What is your age? [Feedback]                                                                             0 non-null      float64
 8   3. How long have you been living in Ireland?                                                                41 non-null     str
 9   3. How long have you been living in Ireland?  [Score]                                                       41 non-null     str
 10  3. How long have you been living in Ireland?  [Feedback]                                                    0 non-null      float64
 11  4. Which county do you currently live in?                                                                   41 non-null     str
 12  4. Which county do you currently live in?  [Score]                                                          41 non-null     str
 13  4. Which county do you currently live in?  [Feedback]                                                       0 non-null      float64
 14  5. What best describes your current living area?                                                            41 non-null     str
 15  5. What best describes your current living area? [Score]                                                    41 non-null     str
 16  5. What best describes your current living area? [Feedback]                                                 0 non-null      float64
 17  6. What is your household situation?                                                                        41 non-null     str
 18  6. What is your household situation? [Score]                                                                41 non-null     str
 19  6. What is your household situation? [Feedback]                                                             0 non-null      float64
 20  7. Do you have a car in Ireland?                                                                            41 non-null     str
 21  7. Do you have a car in Ireland? [Score]                                                                    41 non-null     str
 22  7. Do you have a car in Ireland? [Feedback]                                                                 0 non-null      float64
 23  8. Would you prefer to spend next holiday in Ireland or abroad?                                             41 non-null     str
 24  8. Would you prefer to spend next holiday in Ireland or abroad? [Score]                                     41 non-null     str
 25  8. Would you prefer to spend next holiday in Ireland or abroad? [Feedback]                                  0 non-null      float64
 26  9. How many leisure trips have you taken in the last 12 months, both within Ireland and abroad?             41 non-null     int64
 27  9. How many leisure trips have you taken in the last 12 months, both within Ireland and abroad? [Score]     41 non-null     str
 28  9. How many leisure trips have you taken in the last 12 months, both within Ireland and abroad? [Feedback]  0 non-null      float64
 29  10. What type of leisure trip do you prefer?                                                                41 non-null     str
 30  10. What type of leisure trip do you prefer? [Score]                                                        41 non-null     str
 31  10. What type of leisure trip do you prefer? [Feedback]                                                     0 non-null      float64
 32  11. Who do you usually travel with?                                                                         41 non-null     str
 33  11. Who do you usually travel with? [Score]                                                                 41 non-null     str
 34  11. Who do you usually travel with? [Feedback]                                                              0 non-null      float64
 35  12. What is the main purpose of your leisure trips?                                                         41 non-null     str
 36  12. What is the main purpose of your leisure trips? [Score]                                                 41 non-null     str
 37  12. What is the main purpose of your leisure trips? [Feedback]                                              0 non-null      float64
 38  13. How many leisure trips within Ireland have you taken in the last 12 months?                             41 non-null     int64
 39  13. How many leisure trips within Ireland have you taken in the last 12 months?  [Score]                    41 non-null     str
 40  13. How many leisure trips within Ireland have you taken in the last 12 months?  [Feedback]                 0 non-null      float64
 41  14. What type of Irish destination do you prefer?                                                           41 non-null     str
 42  14. What type of Irish destination do you prefer? [Score]                                                   41 non-null     str
 43  14. What type of Irish destination do you prefer? [Feedback]                                                0 non-null      float64
 44  15. What is your preferred way of travelling around Ireland?                                                41 non-null     str
 45  15. What is your preferred way of travelling around Ireland? [Score]                                        41 non-null     str
 46  15. What is your preferred way of travelling around Ireland? [Feedback]                                     0 non-null      float64
 47  16. What is the typical length of your leisure trip within Ireland?                                         41 non-null     str
 48  16. What is the typical length of your leisure trip within Ireland? [Score]                                 41 non-null     str
 49  16. What is the typical length of your leisure trip within Ireland? [Feedback]                              0 non-null      float64
 50  17. Which counties in Ireland have you visited for leisure?                                                 41 non-null     str
 51  17. Which counties in Ireland have you visited for leisure? [Score]                                         41 non-null     str
 52  17. Which counties in Ireland have you visited for leisure? [Feedback]                                      0 non-null      float64
 53  18. Overall, how satisfied are you with the opportunities to explore Ireland?                               41 non-null     int64
 54  18. Overall, how satisfied are you with the opportunities to explore Ireland?  [Score]                      41 non-null     str
 55  18. Overall, how satisfied are you with the opportunities to explore Ireland?  [Feedback]                   0 non-null      float64
dtypes: float64(18), int64(5), str(33)
memory usage: 32.7 KB

In [7]:
# Clean columns with NA values (If a column contains ONLY NA values)
clean_df = df.dropna(axis=1, how="all")

# Clean columns [Score] where all values are '-- / 0'
score_cols = [c for c in clean_df.columns if c.endswith("[Score]")]

all_blank = clean_df[score_cols].apply(lambda s: s.str.strip().eq("-- / 0").all())

clean_df = clean_df.drop(columns=all_blank[all_blank].index)

# Remove 'Total score' column
clean_df = clean_df.drop(columns="Total score")

In [10]:
# Having a look at the cleaned dataset
clean_df.shape

(41, 19)

In [11]:
clean_df

,Unnamed: 0,1. What is your gender?,2. What is your age?,3. How long have you been living in Ireland?,4. Which county do you currently live in?,5. What best describes your current living area?,6. What is your household situation?,7. Do you have a car in Ireland?,8. Would you prefer to spend next holiday in Ireland or abroad?,"9. How many leisure trips have you taken in the last 12 months, both within Ireland and abroad?",10. What type of leisure trip do you prefer?,11. Who do you usually travel with?,12. What is the main purpose of your leisure trips?,13. How many leisure trips within Ireland have you taken in the last 12 months?,14. What type of Irish destination do you prefer?,15. What is your preferred way of travelling around Ireland?,16. What is the typical length of your leisure trip within Ireland?,17. Which counties in Ireland have you visited for leisure?,"18. Overall, how satisfied are you with the opportunities to explore Ireland?"
0,0,Male,27,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,14,Longer holidays,Partner / Spouse,Relaxation,14,Mountains and countryside,Train,4 - 7 nights,Cork;Donegal;Dublin;Galway;Kerry;Kildare;Kilke...,5
1,1,Male,28,I was born in Ireland,Cork,Small / Medium-sized town,Living with family / children,No,Abroad,3,Weekend breaks,Alone,Relaxation,0,Abroad,Combination of transport,One day/ No overnight stay,Cork;Dublin;Kildare,5
2,2,Male,55,I was born in Ireland,Donegal,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,3,Longer holidays,Partner / Spouse,Relaxation,2,Cities and towns,Personal car,2 - 3 nights,Cork;Donegal;Dublin;Galway;Kerry;Mayo;Sligo;We...,4
3,3,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,Family,Exploring new places,2,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3
4,4,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,Family,Exploring new places,2,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3
5,5,Male,28,I was born in Ireland,Cork,Large city,Living with a partner / spouse,Yes,Abroad,5,Day trips,Partner / Spouse,Relaxation,3,Coastal areas and beaches,Personal car,2 - 3 nights,Clare;Cork;Dublin;Galway;Kerry;Limerick;Mayo;W...,4
6,6,Female,39,5 - 6 years,Dublin,Large city,Living with a partner / spouse,No,Abroad,3,Weekend breaks,Partner / Spouse,Relaxation,3,Coastal areas and beaches,Personal car,One day/ No overnight stay,Kildare;Kilkenny;Waterford;Wexford;Wicklow,4
7,7,Male,36,1 - 2 years,Mayo,Village,Sharing accommodation with friends / housemates,No,Ireland,0,Weekend breaks,Friends,Exploring new places,3,A combination of these,Combination of transport,One day/ No overnight stay,Carlow;Cork;Donegal;Dublin;Galway;Limerick;May...,4
8,8,Male,29,3 - 4 years,Dublin,Large city,Living with a partner / spouse,No,Abroad,3,Longer holidays,Partner / Spouse,Exploring new places,0,Coastal areas and beaches,Combination of transport,2 - 3 nights,Clare;Cork;Dublin;Galway;Wicklow,3
9,9,Female,41,10 + years,Dublin,Dublin (small city),Sharing accommodation with friends / housemates,Yes,Abroad,5,A combination of these,Alone,Exploring new places,1,A combination of these,Personal car,1 night,Clare;Cork;Donegal;Dublin;Galway;Kerry;Kildare...,5
10,10,Male,35,9 - 10 years,Limerick,Large city,Living with a partner / spouse,Yes,Abroad,7,Longer holidays,Partner / Spouse,Exploring new places,4,National parks and nature reserves,Personal car,One day/ No overnight stay,Cavan;Clare;Cork;Dublin;Galway;Kerry;Kildare;L...,3
11,11,Female,36,7 - 8 years,Cork,Small / Medium-sized town,Living with family / children,Yes,Abroad,4,A combination of these,Family,Exploring new places,3,Coastal areas and beaches,Personal car,2 - 3 nights,Donegal;Dublin;Kerry;Kildare;Wicklow,5
12,12,Female,26,3 - 4 years,Dublin,Small / Medium-sized town,Sharing accommodation with friends / housemates,No,Abroad,6,Longer holidays,Friends,Exploring new places,2,Cities and towns,Rental car,1 night,Cork;Dublin;Galway;Kildare;Kilkenny;Limerick;M...,3
13,13,Female,40,3 - 4 years,Kildare,Village,Living with family / children,No,Abroad,1,Longer holidays,Family,Exploring new places,1,A combination of these,Combination of transport,One day/ No overnight stay,Dublin;Kildare;Waterford,3
14,14,Female,30,3 - 4 years,Dublin,Small / Medium-sized town,Living with a partner / spouse,No,Abroad,0,Longer holidays,Partner / Spouse,Exploring new places,3,Coastal areas and beaches,Walking/Hiking,One day/ No overnight stay,Dublin;Kilkenny;Wicklow,5
15,15,Male,33,9 - 10 years,Dublin,Large city,Sharing accommodation with friends / housemates,Yes,Abroad,2,Longer holidays,Partner / Spouse,Exploring new places,0,Coastal areas and beaches,Personal car,2 - 3 nights,Cork;Dublin;Galway;Kerry;Kildare;Wexford;Wicklow,4
16,16,Male,49,10 + years,Laois,Small / Medium-sized town,Living with family / children,Yes,Abroad,2,Longer holidays,Family,Visiting friends and family,2,Coastal areas and beaches,Personal car,2 - 3 nights,Clare;Cork;Donegal;Kerry;Kilkenny;Limerick;Mea...,4
17,17,Male,27,I was born in Ireland,Laois,Rural area,Living with family / children,Yes,Abroad,3,A combination of these,Friends,Relaxation,1,Coastal areas and beaches,Personal car,2 - 3 nights,Cork;Dublin;Galway;Sligo;Waterford;Wexford,4
18,18,Male,32,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,5,A combination of these,Friends,Exploring new places,3,A combination of these,Rental car,One day/ No overnight stay,Cork;Dublin;Galway;Kildare;Kilkenny;Waterford;...,3
19,19,Female,33,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,Yes,Ireland,4,Weekend breaks,Alone,Visiting friends and family,20,A combination of these,Personal car,One day/ No overnight stay,Carlow;Dublin;Galway;Kildare;Kilkenny;Limerick...,5
20,20,Male,39,3 - 4 years,Wexford,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,4,A combination of these,Partner / Spouse,Exploring new places,2,A combination of these,Personal car,One day/ No overnight stay,Carlow;Cork;Dublin;Kerry;Kildare;Kilkenny;Lime...,4
21,21,Female,42,10 + years,Dublin,Large city,Living with a partner / spouse,Yes,Abroad,3,Longer holidays,Partner / Spouse,Relaxation,3,Coastal areas and beaches,Personal car,2 - 3 nights,Clare;Cork;Galway;Kildare;Mayo;Wexford;Wicklow,5
22,22,Female,44,3 - 4 years,Dublin,Large city,Living with a partner / spouse,No,Abroad,7,Day trips,Partner / Spouse,Exploring new places,3,National parks and nature reserves,Train,One day/ No overnight stay,Cork;Kerry;Kildare,3
23,23,Female,36,10 + years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,3,A combination of these,Friends,Exploring new places,1,Mountains and countryside,Rental car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kerry;...,4
24,24,Male,32,I was born in Ireland,Carlow,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,2,A combination of these,Partner / Spouse,Exploring new places,3,Coastal areas and beaches,Personal car,1 night,Clare;Cork;Donegal;Dublin;Galway;Kerry;Kilkenn...,5
25,25,Female,36,9 - 10 years,Cork,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,Family,Relaxation,3,Coastal areas and beaches,Personal car,2 - 3 nights,Donegal;Kerry;Sligo,5
26,26,Male,36,1 - 2 years,Mayo,Large city,Sharing accommodation with friends / housemates,No,Ireland,2,Day trips,Friends,Exploring new places,2,Mountains and countryside,Combination of transport,One day/ No overnight stay,Cork;Donegal;Dublin;Galway;Limerick;Mayo;Rosco...,4
27,27,Male,40,3 - 4 years,Kildare,Rural area,Living with family / children,Yes,Abroad,2,Longer holidays,Family,Exploring new places,2,A combination of these,Personal car,One day/ No overnight stay,Cork;Dublin;Kildare;Waterford,3
28,28,Non-binary,48,I was born in Ireland,Wicklow,Village,Living with family / children,Yes,Abroad,3,A combination of these,Partner / Spouse,Relaxation,1,Coastal areas and beaches,Personal car,2 - 3 nights,Carlow;Cork;Donegal;Dublin;Galway;Kerry;Kildar...,3
29,29,Female,26,5 - 6 years,Dublin,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,2,Weekend breaks,Partner / Spouse,Exploring new places,5,A combination of these,Personal car,1 night,Carlow;Cavan;Cork;Dublin;Galway;Kildare;Limeri...,4
30,30,Male,32,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,5,A combination of these,Friends,Exploring new places,3,A combination of these,Rental car,One day/ No overnight stay,Cork;Dublin;Galway;Kildare;Kilkenny;Limerick;M...,5
31,31,Male,33,9 - 10 years,Dublin,Small / Medium-sized town,Sharing accommodation with friends / housemates,Yes,Abroad,2,Longer holidays,Partner / Spouse,Exploring new places,1,Coastal areas and beaches,Personal car,2 - 3 nights,Dublin;Kerry;Kildare;Wicklow,3
32,32,Female,41,10 + years,Dublin,"Small city, Dublin",Sharing accommodation with friends / housemates,Yes,Abroad,5,A combination of these,Friends,Exploring new places,1,A combination of these,Personal car,2 - 3 nights,Cavan;Clare;Cork;Donegal;Dublin;Galway;Kerry;K...,5
33,33,Female,31,10 + years,Cork,Village,Living with family / children,Yes,Abroad,3,Longer holidays,Family,Relaxation,0,A combination of these,Personal car,1 night,Cork;Dublin;Galway;Kerry;Kilkenny;Limerick;Sli...,5
34,34,Male,27,3 - 4 years,Dublin,Large city,Living with a partner / spouse,Yes,Abroad,3,Longer holidays,Partner / Spouse,Exploring new places,1,Coastal areas and beaches,Personal car,One day/ No overnight stay,Clare;Cork;Donegal;Kerry;Kilkenny;Mayo;Waterfo...,3
35,35,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,A combination of these,Family,Exploring new places,2,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kilken...,3
36,36,Female,43,10 + years,Dublin,Large city,Living with family / children,Yes,Abroad,5,A combination of these,Family,All of the above,3,A combination of these,Personal car,1 night,Clare;Cork;Donegal;Dublin;Galway;Kerry;Kildare...,5
37,37,Male,30,3 - 4 years,Dublin,Large city,Living with a partner / spouse,Yes,Abroad,2,Longer holidays,Partner / Spouse,Relaxation,0,National parks and nature reserves,Personal car,One day/ No overnight stay,Dublin;Wicklow,3
38,38,Male,35,10 + years,Dublin,Large city,Living with a partner / spouse,No,Abroad,3,Longer holidays,Partner / Spouse,Exploring new places,3,A combination of these,Combination of transport,2 - 3 nights,Dublin;Kerry,5
39,39,Female,26,I was born in Ireland,Cork,Large city,Sharing accommodation with friends / housemates,No,Abroad,5,Longer holidays,Alone,Exploring new places,2,Historical sites and castles,Train,One day/ No overnight stay,Clare;Cork;Dublin;Galway;Kerry;Kildare;Leitrim...,5
40,40,Male,39,3 - 4 years,Wexford,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,5,A combination of these,Partner / Spouse,Exploring new places,2,A combination of these,Personal car,One day/ No overnight stay,Carlow;Cork;Dublin;Kerry;Kildare;Kilkenny;Lime...,4

In [14]:
# Check how many unique values has every column (NaN is a value)
clean_df.nunique(dropna=False)

Unnamed: 0                                                                                         41
1. What is your gender?                                                                             3
2. What is your age?                                                                               19
3. How long have you been living in Ireland?                                                        7
4. Which county do you currently live in?                                                          10
5. What best describes your current living area?                                                    6
6. What is your household situation?                                                                3
7. Do you have a car in Ireland?                                                                    2
8. Would you prefer to spend next holiday in Ireland or abroad?                                     2
9. How many leisure trips have you taken in the last 12 months, both within Ireland and abroad?     9
10. What type of leisure trip do you prefer?                                                        4
11. Who do you usually travel with?                                                                 4
12. What is the main purpose of your leisure trips?                                                 4
13. How many leisure trips within Ireland have you taken in the last 12 months?                     8
14. What type of Irish destination do you prefer?                                                   7
15. What is your preferred way of travelling around Ireland?                                        5
16. What is the typical length of your leisure trip within Ireland?                                 4
17. Which counties in Ireland have you visited for leisure?                                        40
18. Overall, how satisfied are you with the opportunities to explore Ireland?                       3
dtype: int64